# Generated by Django 4.2.6 on 2023-10-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_lesson',
        ),
    ]
