# Generated by Django 4.2.6 on 2023-10-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_payment_paid_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=32000, verbose_name='Price'),
        ),
    ]
